spring.application.name=deal

logging.level.root=INFO
logging.level.ru.neoflex.deal=DEBUG
logging.file.name=logs/dealservice.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{requestId}] %-5level %logger{36} - %msg%n

calculator.calcservice.url=http://localhost:8080

spring.datasource.url=jdbc:postgresql://localhost:5432/dealservice_db
spring.datasource.username=dealservice_user
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db/changelog-master.xml
