spring.application.name=deal
server.port=8080

logging.level.root=INFO
logging.level.ru.neoflex.deal=DEBUG
logging.file.name=logs/dealservice.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{requestId}] %-5level %logger{36} - %msg%n

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml

spring.datasource.url=jdbc:postgresql://localhost:5432/dealservice_db
spring.datasource.username=dealservice_user
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

calculator.calcservice.url=http://localhost:8081
