spring.application.name=calcservice

calculator.insuranceCostMultiplier=0.01
calculator.insurancePacketCost=10000
calculator.commissionRate = 0.4
calculator.baseRate=0.25
calculator.minRate = 0.20
calculator.salaryClientDiscount=0.02
calculator.insurancePercentDiscount=0.01