spring.application.name=calcservice

logging.level.root=INFO
logging.level.ru.neoflex.calcservice=DEBUG
logging.file.name=logs/calcservice.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{requestId}] %-5level %logger{36} - %msg%n

server.port=8081

calculator.insuranceCostMultiplier=0.01
calculator.insurancePacketCost=10000
calculator.commissionRate = 0.4
calculator.baseRate=0.25
calculator.minRate = 0.20
calculator.salaryClientDiscount=0.02
calculator.insurancePercentDiscount=0.01
calculator.smallCreditLimit=500000