server.port=8081
spring.application.name=dossier

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=dossier-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=emailMessage:ru.neoflex.dossier.dto.EmailMessage
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=ru.neoflex.dossier.dto.EmailMessage

kafka.topic.send-documents=send-documents

spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.username=admin
spring.mail.password=admin
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

logging.level.org.springframework.kafka=INFO